name: PESLIB automated test for all PES
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        python-version: ['3.9', '3.10', '3.11' ]
    runs-on: ${{ matrix.os }}
    env:
      CI: true
      FC: gfortran
      # Help find libraries
      LIBRARY_DIRS: /usr/lib/x86_64-linux-gnu
      # Explicitly set LD_LIBRARY_PATH to help find runtime libraries
      LD_LIBRARY_PATH: /usr/lib/x86_64-linux-gnu
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gfortran libblas-dev liblapack-dev libblas3 liblapack3 build-essential
        # Create symbolic links if needed for libraries
        sudo ln -sf /usr/lib/x86_64-linux-gnu/libblas.so /usr/lib/libblas.so
        sudo ln -sf /usr/lib/x86_64-linux-gnu/liblapack.so /usr/lib/liblapack.so
        # Show available libraries for debugging
        ldconfig -p | grep -E '(blas|lapack)'
        
    - name: Install Python build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel setuptools "numpy<1.25.0"

    - name: Install package
      run: |
        # Set environment variables to help find libraries
        export LIBRARY_PATH=$LIBRARY_PATH:/usr/lib/x86_64-linux-gnu
        pip install -v .

    - name: Run pytest
      run: |
        pip install pytest
        cd tests
        pytest . -v