name: PESLIB automated test for all PES
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        python-version: ['3.9', '3.10', '3.11' ]
    runs-on: ${{ matrix.os }}
    env:
      CI: true
      FC: gfortran
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gfortran libblas-dev liblapack-dev libblas3 liblapack3 build-essential
        
    - name: Install Python build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel setuptools "numpy<1.25.0"

    - name: Install dependencies
      run: |
        pip install . 

    - name: Run pytest
      run: |
        pip install pytest
        cd tests
        pytest . -v